CREATE TABLE image_metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL,
    "path" TEXT NOT NULL,
    format TEXT,
    mode TEXT,
    width INTEGER,
    height INTEGER,
    capture_date TEXT,
    software TEXT,
    make TEXT,
    model TEXT,
    lens_model TEXT,
    iso INTEGER,
    exposure_time TEXT,
    dpi_x INTEGER,
    dpi_y INTEGER,
    icc_profile TEXT,
    gps_latitude TEXT,
    gps_longitude TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file_id) REFERENCES home_file(id),
    UNIQUE (file_id, "path")
);