CREATE TABLE image_metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL,
    "path" TEXT NOT NULL,
    format TEXT,
    mode TEXT,
    width INTEGER,
    height INTEGER,
    dpi_x REAL,
    dpi_y REAL,
    x_resolution REAL,
    y_resolution REAL,
    resolution_unit REAL,
    orientation REAL,
    compression REAL,
    photometric_interpretation REAL,
    color_space REAL,
    components_configuration TEXT,
    icc_profile TEXT,
    make TEXT,
    model TEXT,
    software TEXT,
    lens_model TEXT,
    serial_number TEXT,
    datetime TEXT,
    datetime_original TEXT,
    datetime_digitized TEXT,
    subsec_time TEXT,
    exposure_time REAL,
    f_number REAL,
    iso REAL,
    shutter_speed REAL,
    aperture_value REAL,
    brightness_value REAL,
    exposure_bias REAL,
    metering_mode REAL,
    flash REAL,
    focal_length REAL,
    white_balance REAL,
    exposure_program REAL,
    max_aperture_value REAL,
    gps_latitude REAL,
    gps_longitude REAL,
    gps_altitude REAL,
    gps_date TEXT,
    gps_time TEXT,
    image_description TEXT,
    user_comment TEXT,
    copyright TEXT,
    artist TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file_id) REFERENCES home_file(id),
    UNIQUE (file_id, "path")
);