CREATE TABLE audio_metadata (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL,
    "path" TEXT NOT NULL,
    mime TEXT,
    length REAL,
    bitrate INTEGER,
    sample_rate INTEGER,
    channels INTEGER,
    bitrate_mode INTEGER,
    encoder_info TEXT,
    bit_depth INTEGER,
    title TEXT,
    artist TEXT,
    album TEXT,
    album_artist TEXT,
    track_number TEXT,
    genre TEXT,
    composer TEXT,
    year TEXT,
    recording_date TEXT,
    encoder TEXT,
    publisher TEXT,
    original_release_date TEXT,
    original_artist TEXT,
    lyricist TEXT,
    lyrics TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file_id) REFERENCES home_file(id),
    UNIQUE (file_id, "path")
);