CREATE TABLE
    video_metadata (
        id SERIAL PRIMARY KEY,
        file_id INTEGER NOT NULL,
        PATH TEXT NOT NULL,
        format_name TEXT,
        size TEXT,
        duration TEXT,
        WIDTH INTEGER,
        HEIGHT INTEGER,
        frame_rate REAL,
        nb_frames INTEGER,
        bit_rate TEXT,
        codec_name TEXT,
        codec_long_name TEXT,
        pix_fmt TEXT,
        LEVEL INTEGER,
        profile TEXT,
        aspect_ratio TEXT,
        audio_codec TEXT,
        audio_channels INTEGER,
        audio_sample_rate TEXT,
        audio_bit_rate TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (file_id) REFERENCES home_file (id),
        UNIQUE (file_id, PATH)
    );