ALTER TABLE video_playlist
    ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_auto BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS group_mode VARCHAR(20) NOT NULL DEFAULT 'folder',
    ADD COLUMN IF NOT EXISTS classification VARCHAR(20) NOT NULL DEFAULT 'personal';

ALTER TABLE video_playlist_item
    ADD COLUMN IF NOT EXISTS source_kind VARCHAR(10) NOT NULL DEFAULT 'auto';

CREATE TABLE IF NOT EXISTS video_playlist_exclusion (
    id SERIAL PRIMARY KEY,
    playlist_id INTEGER NOT NULL REFERENCES video_playlist(id) ON DELETE CASCADE,
    video_id INTEGER NOT NULL REFERENCES home_file(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (playlist_id, video_id)
);
