ALTER TABLE captures
    ADD COLUMN IF NOT EXISTS file_id INTEGER REFERENCES home_file (id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'uploaded',
    ADD COLUMN IF NOT EXISTS title VARCHAR(512) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS episode_title VARCHAR(512) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS season INTEGER,
    ADD COLUMN IF NOT EXISTS episode INTEGER,
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS release_year INTEGER,
    ADD COLUMN IF NOT EXISTS genres JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS cast_members JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS directors JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS studio VARCHAR(256) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS content_rating VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS platform VARCHAR(128) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS source_url VARCHAR(2048) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS thumbnail_url VARCHAR(2048) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS content_type VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS raw_metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_captures_file_id ON captures (file_id);
CREATE INDEX IF NOT EXISTS idx_captures_status ON captures (status);
