INSERT INTO
    audio_metadata (
        file_id,
        "path",
        mime,
        length,
        bitrate,
        sample_rate,
        channels,
        bitrate_mode,
        encoder_info,
        bit_depth,
        title,
        artist,
        album,
        album_artist,
        track_number,
        genre,
        composer,
        year,
        recording_date,
        encoder,
        publisher,
        original_release_date,
        original_artist,
        lyricist,
        lyrics,
        created_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT (file_id, "path") DO
UPDATE
SET
    mime = EXCLUDED.mime,
    length = EXCLUDED.length,
    bitrate = EXCLUDED.bitrate,
    sample_rate = EXCLUDED.sample_rate,
    channels = EXCLUDED.channels,
    bitrate_mode = EXCLUDED.bitrate_mode,
    encoder_info = EXCLUDED.encoder_info,
    bit_depth = EXCLUDED.bit_depth,
    title = EXCLUDED.title,
    artist = EXCLUDED.artist,
    album = EXCLUDED.album,
    album_artist = EXCLUDED.album_artist,
    track_number = EXCLUDED.track_number,
    genre = EXCLUDED.genre,
    composer = EXCLUDED.composer,
    year = EXCLUDED.year,
    recording_date = EXCLUDED.recording_date,
    encoder = EXCLUDED.encoder,
    publisher = EXCLUDED.publisher,
    original_release_date = EXCLUDED.original_release_date,
    original_artist = EXCLUDED.original_artist,
    lyricist = EXCLUDED.lyricist,
    lyrics = EXCLUDED.lyrics RETURNING id,
    created_at;