INSERT INTO
    image_metadata (
        file_id,
        PATH,
        FORMAT,
        MODE,
        WIDTH,
        HEIGHT,
        dpi_x,
        dpi_y,
        x_resolution,
        y_resolution,
        resolution_unit,
        orientation,
        COMPRESSION,
        photometric_interpretation,
        color_space,
        components_configuration,
        icc_profile,
        make,
        model,
        software,
        lens_model,
        serial_number,
        datetime,
        datetime_original,
        datetime_digitized,
        subsec_time,
        exposure_time,
        f_number,
        iso,
        shutter_speed,
        aperture_value,
        brightness_value,
        exposure_bias,
        metering_mode,
        flash,
        focal_length,
        white_balance,
        exposure_program,
        max_aperture_value,
        gps_latitude,
        gps_longitude,
        gps_altitude,
        gps_date,
        gps_time,
        image_description,
        user_comment,
        copyright,
        artist,
        created_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35,
        $36,
        $37,
        $38,
        $39,
        $40,
        $41,
        $42,
        $43,
        $44,
        $45,
        $46,
        $47,
        $48,
        $49
    ) ON CONFLICT (file_id, PATH)
DO
UPDATE
SET
    FORMAT = EXCLUDED.format,
    MODE = EXCLUDED.mode,
    WIDTH = EXCLUDED.width,
    HEIGHT = EXCLUDED.height,
    dpi_x = EXCLUDED.dpi_x,
    dpi_y = EXCLUDED.dpi_y,
    x_resolution = EXCLUDED.x_resolution,
    y_resolution = EXCLUDED.y_resolution,
    resolution_unit = EXCLUDED.resolution_unit,
    orientation = EXCLUDED.orientation,
    COMPRESSION = EXCLUDED.compression,
    photometric_interpretation = EXCLUDED.photometric_interpretation,
    color_space = EXCLUDED.color_space,
    components_configuration = EXCLUDED.components_configuration,
    icc_profile = EXCLUDED.icc_profile,
    make = EXCLUDED.make,
    model = EXCLUDED.model,
    software = EXCLUDED.software,
    lens_model = EXCLUDED.lens_model,
    serial_number = EXCLUDED.serial_number,
    datetime = EXCLUDED.datetime,
    datetime_original = EXCLUDED.datetime_original,
    datetime_digitized = EXCLUDED.datetime_digitized,
    subsec_time = EXCLUDED.subsec_time,
    exposure_time = EXCLUDED.exposure_time,
    f_number = EXCLUDED.f_number,
    iso = EXCLUDED.iso,
    shutter_speed = EXCLUDED.shutter_speed,
    aperture_value = EXCLUDED.aperture_value,
    brightness_value = EXCLUDED.brightness_value,
    exposure_bias = EXCLUDED.exposure_bias,
    metering_mode = EXCLUDED.metering_mode,
    flash = EXCLUDED.flash,
    focal_length = EXCLUDED.focal_length,
    white_balance = EXCLUDED.white_balance,
    exposure_program = EXCLUDED.exposure_program,
    max_aperture_value = EXCLUDED.max_aperture_value,
    gps_latitude = EXCLUDED.gps_latitude,
    gps_longitude = EXCLUDED.gps_longitude,
    gps_altitude = EXCLUDED.gps_altitude,
    gps_date = EXCLUDED.gps_date,
    gps_time = EXCLUDED.gps_time,
    image_description = EXCLUDED.image_description,
    user_comment = EXCLUDED.user_comment,
    copyright = EXCLUDED.copyright,
    artist = EXCLUDED.artist
RETURNING
    id,
    created_at;