INSERT INTO
    image_metadata (
        file_id,
        "path",
        format,
        mode,
        width,
        height,
        dpi_x,
        dpi_y,
        x_resolution,
        y_resolution,
        resolution_unit,
        orientation,
        compression,
        photometric_interpretation,
        color_space,
        components_configuration,
        icc_profile,
        make,
        model,
        software,
        lens_model,
        serial_number,
        datetime,
        datetime_original,
        datetime_digitized,
        subsec_time,
        exposure_time,
        f_number,
        iso,
        shutter_speed,
        aperture_value,
        brightness_value,
        exposure_bias,
        metering_mode,
        flash,
        focal_length,
        white_balance,
        exposure_program,
        max_aperture_value,
        gps_latitude,
        gps_longitude,
        gps_altitude,
        gps_date,
        gps_time,
        image_description,
        user_comment,
        copyright,
        artist,
        created_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT (file_id, "path") DO
UPDATE
SET
    format = excluded.format,
    mode = excluded.mode,
    width = excluded.width,
    height = excluded.height,
    dpi_x = excluded.dpi_x,
    dpi_y = excluded.dpi_y,
    x_resolution = excluded.x_resolution,
    y_resolution = excluded.y_resolution,
    resolution_unit = excluded.resolution_unit,
    orientation = excluded.orientation,
    compression = excluded.compression,
    photometric_interpretation = excluded.photometric_interpretation,
    color_space = excluded.color_space,
    components_configuration = excluded.components_configuration,
    icc_profile = excluded.icc_profile,
    make = excluded.make,
    model = excluded.model,
    software = excluded.software,
    lens_model = excluded.lens_model,
    serial_number = excluded.serial_number,
    datetime = excluded.datetime,
    datetime_original = excluded.datetime_original,
    datetime_digitized = excluded.datetime_digitized,
    subsec_time = excluded.subsec_time,
    exposure_time = excluded.exposure_time,
    f_number = excluded.f_number,
    iso = excluded.iso,
    shutter_speed = excluded.shutter_speed,
    aperture_value = excluded.aperture_value,
    brightness_value = excluded.brightness_value,
    exposure_bias = excluded.exposure_bias,
    metering_mode = excluded.metering_mode,
    flash = excluded.flash,
    focal_length = excluded.focal_length,
    white_balance = excluded.white_balance,
    exposure_program = excluded.exposure_program,
    max_aperture_value = excluded.max_aperture_value,
    gps_latitude = excluded.gps_latitude,
    gps_longitude = excluded.gps_longitude,
    gps_altitude = excluded.gps_altitude,
    gps_date = excluded.gps_date,
    gps_time = excluded.gps_time,
    image_description = excluded.image_description,
    user_comment = excluded.user_comment,
    copyright = excluded.copyright,
    artist = excluded.artist RETURNING id,
    created_at;