INSERT INTO
    video_metadata (
        file_id,
        "path",
        format_name,
        "size",
        duration,
        width,
        height,
        frame_rate,
        nb_frames,
        bit_rate,
        codec_name,
        codec_long_name,
        pix_fmt,
        "level",
        "profile",
        aspect_ratio,
        audio_codec,
        audio_channels,
        audio_sample_rate,
        audio_bit_rate,
        created_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT (file_id, "path") DO
UPDATE
SET
    format_name = EXCLUDED.format_name,
    size = EXCLUDED.size,
    duration = EXCLUDED.duration,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    frame_rate = EXCLUDED.frame_rate,
    nb_frames = EXCLUDED.nb_frames,
    bit_rate = EXCLUDED.bit_rate,
    codec_name = EXCLUDED.codec_name,
    codec_long_name = EXCLUDED.codec_long_name,
    pix_fmt = EXCLUDED.pix_fmt,
    "level" = EXCLUDED.level,
    "profile" = EXCLUDED.profile,
    aspect_ratio = EXCLUDED.aspect_ratio,
    audio_codec = EXCLUDED.audio_codec,
    audio_channels = EXCLUDED.audio_channels,
    audio_sample_rate = EXCLUDED.audio_sample_rate,
    audio_bit_rate = EXCLUDED.audio_bit_rate RETURNING id,
    created_at;