INSERT INTO
    image_metadata (
        file_id,
        "path",
        format,
        mode,
        width,
        height,
        capture_date,
        software,
        make,
        model,
        lens_model,
        iso,
        exposure_time,
        dpi_x,
        dpi_y,
        icc_profile,
        gps_latitude,
        gps_longitude,
        created_at
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT (file_id, "path") DO
UPDATE
SET
    format = EXCLUDED.format,
    mode = EXCLUDED.mode,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    capture_date = EXCLUDED.capture_date,
    software = EXCLUDED.software,
    make = EXCLUDED.make,
    model = EXCLUDED.model,
    lens_model = EXCLUDED.lens_model,
    iso = EXCLUDED.iso,
    exposure_time = EXCLUDED.exposure_time,
    dpi_x = EXCLUDED.dpi_x,
    dpi_y = EXCLUDED.dpi_y,
    icc_profile = EXCLUDED.icc_profile,
    gps_latitude = EXCLUDED.gps_latitude,
    gps_longitude = EXCLUDED.gps_longitude RETURNING id,
    created_at;