SELECT
    hf.id,
    hf."name",
    hf."path",
    hf.parent_path,
    hf.format,
    hf."size",
    hf.updated_at,
    hf.created_at,
    hf.last_interaction,
    hf.last_backup,
    hf."type",
    hf.checksum,
    hf.deleted_at,
    hf.starred,
    COALESCE(im.id, 0),
    COALESCE(im.file_id, 0),
    COALESCE(im."path", ''),
    COALESCE(im.FORMAT, ''),
    COALESCE(im."mode", ''),
    COALESCE(im.WIDTH, 0),
    COALESCE(im.HEIGHT, 0),
    COALESCE(im.dpi_x, 0),
    COALESCE(im.dpi_y, 0),
    COALESCE(im.x_resolution, 0),
    COALESCE(im.y_resolution, 0),
    COALESCE(im.resolution_unit, 0),
    COALESCE(im.orientation, 0),
    COALESCE(im."compression", 0),
    COALESCE(im.photometric_interpretation, 0),
    COALESCE(im.color_space, 0),
    COALESCE(im.components_configuration, ''),
    COALESCE(im.icc_profile, ''),
    COALESCE(im.make, ''),
    COALESCE(im.model, ''),
    COALESCE(im.software, ''),
    COALESCE(im.lens_model, ''),
    COALESCE(im.serial_number, ''),
    COALESCE(im.datetime, ''),
    COALESCE(im.datetime_original, ''),
    COALESCE(im.datetime_digitized, ''),
    COALESCE(im.subsec_time, ''),
    COALESCE(im.exposure_time, 0),
    COALESCE(im.f_number, 0),
    COALESCE(im.iso, 0),
    COALESCE(im.shutter_speed, 0),
    COALESCE(im.aperture_value, 0),
    COALESCE(im.brightness_value, 0),
    COALESCE(im.exposure_bias, 0),
    COALESCE(im.metering_mode, 0),
    COALESCE(im.flash, 0),
    COALESCE(im.focal_length, 0),
    COALESCE(im.white_balance, 0),
    COALESCE(im.exposure_program, 0),
    COALESCE(im.max_aperture_value, 0),
    COALESCE(im.gps_latitude, 0),
    COALESCE(im.gps_longitude, 0),
    COALESCE(im.gps_altitude, 0),
    COALESCE(im.gps_date, ''),
    COALESCE(im.gps_time, ''),
    COALESCE(im.image_description, ''),
    COALESCE(im.user_comment, ''),
    COALESCE(im.copyright, ''),
    COALESCE(im.artist, ''),
    COALESCE(im.classification_category, 'other'),
    COALESCE(im.classification_confidence, 0),
    COALESCE(im.classification_suggested_name, ''),
    COALESCE(im.created_at, TIMESTAMPTZ '0001-01-01 00:00:00+00'),
    im.ai_classified_at
FROM
    home_file hf
    LEFT JOIN image_metadata im ON hf.id = im.file_id
WHERE
    hf.format = ANY($1)
    AND hf.deleted_at IS NULL
ORDER BY
    {{ORDER_BY}}
LIMIT
    $2
OFFSET
    $3;
