name: CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  GO_VERSION: '1.21'
  NODE_VERSION: '20'
  FRONTEND_DIR: frontend
  BACKEND_DIR: backend

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install --frozen-lockfile
      - run: yarn test

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go fmt ./...
      - run: go vet ./...

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go test ./...
